--- #YAML:1.0
name:               Catalyst-Plugin-CookiedSession
version:            0.35
abstract:           Store sessions in a browser cookie
author:
    - Leon Brocard <acme@astray.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Exception:  0
    Class::Accessor::Fast:  0
    Crypt::CBC:           0
    Crypt::Rijndael:      0
    JSON::XS::VersionOneAndTwo:  0
    MIME::Base64:         0
    NEXT:                 0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
